### ISSUE TITLE
Cannot connect to Jellyfin behind reverse-proxy (but Android app works)

### ISSUE THREAD

**Issue by ag14774** [jellyfin/jellyfin-webos#122]
Hi all,

I have Jellyfin configured with Traefik in a docker compose file. I have set it up such that "jellyfin.local" routes to the port 8096 of the jellyfin service. When I start the android app the URL "http://jellyfin.local" works fine. However the same URL on the TV (WebOS 5 installed via homebrew) is not working and it says "request timed out". Jellyfin server is v10.8.5.0

Here's an excerpt from the Jellyfin docker config:
```
    ports:
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    environment:
      - TZ=Europe/Zurich
    volumes:
      - jellyfin_config:/config
      - owncloud_webdav:/media
    labels:
      - "traefik.http.routers.localjellyfin.rule=Host(`jellyfin.local`)"
      - "traefik.http.routers.localjellyfin.entrypoints=web"
      # Jellyfin is running on port 8096
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.enable=true"

```

Any ideas what could be going on?
