### ISSUE TITLE
Can't connect to the server anymore on WebOS with HTTPS

### ISSUE THREAD

**Issue by naku** [jellyfin/jellyfin-webos#63]
I can't connect anymore with https, I get stuck on the URL screen with "unable to connect" error.

This coincides with the expiry of Let's Encrypt cross-signed certificate a few months ago (https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/), so I guess the new certificate is not recognized either by Jellyfin or the TV itself.

I'm on WebOS 05.40.09

As a workaround I allowed the server app to be accessed on HTTP, and it worked just fine.

**Comment by ferferga** [comment]
I doubt this is something we can actually fix

**Comment by naku** [comment]
Is this something that should be fixed in WebOS ? How can I diagnose, is there some logs ?

I'm also curious because I can work around the issue by loading Jellyfin in the WebOS browser

**Comment by tabrs** [comment]
I'm curious - my family live in different city and they couldn't log to my Plex server when encrypted connection is required recently. It's weird but I would connect these two issues - it looks like something weird is happening with WebOS.

**Comment by Informatic** [comment]
webOS Browser uses separate trusted CA store to the rest of the OS. So far you have two options:
* Migrate to [ZeroSSL](https://zerossl.com/) which is (so far - still free) alternative to Let's Encrypt that issues certificates signed by UserTrust/Comodo CA, which will be trusted by legacy hardware up until year 2038.
* [Root Your TV](https://rootmy.tv) and [overwrite system CA store](https://gist.github.com/stek29/761232c6f7e1ffbc36b98da2a3a0f4d9)

**Comment by Y0ngg4n** [comment]
same issue here

**Comment by anthonylavado** [comment]
@naku and @Y0ngg4n Was this through the app or just the browser?

As mentioned, we're likely unable to fix this as it depends on the webOS Certificate Authority storage, and unless LG issues an update for that, you'd have to either enable HTTP (even if only for local access), or follow the steps provided by @Informatic (ty for that).

**Comment by naku** [comment]
> @naku and @Y0ngg4n Was this through the app or just the browser?

It works in the browser and not in the app.

I've enabled HTTP as a workaround.

**Comment by anthonylavado** [comment]
Looks like Plex is affected as well.

https://forums.plex.tv/t/important-information-about-plex-for-smart-tvs-after-september-30-2021/746506
https://support.plex.tv/articles/204080173-which-smart-tv-models-are-supported/

>Note: Due to root certificate limitations with the device OS itself, only webOS 5.0+ devices support secure connections with a personal Plex Media Server. To allow connections to a personal server, devices running earlier webOS versions must be set to Allow Insecure Connections in the TV app settings and the Plex Media Server must be set to Preferred for the Secure Connections preference.

Other than suggesting the items above, it looks like we can't correct this. I will try to add a disclaimer/message to our documentation around server TLS and on the readme for this repo.

**Comment by anthonylavado** [comment]
I'll have to dig in further as to how Plex fixed it for webOS 5+ (if they moved everyone to ZeroSSL, specified another chain with Let's Encrypt or what). It sucks that no one is really sharing this info.

**Comment by Informatic** [comment]
Their TLS setup is actually fairly well documented: https://blog.filippo.io/how-plex-is-doing-https-for-all-its-users/

Though I heard they've migrated to Let's Encrypt since that post. Isn't webOS 5+ supporting Let's Encrypt properly with some latest updates? (I am not following that endevours - just throwing a question out there :))

**Comment by anthonylavado** [comment]
I'm very familiar with that page, haha.

Apparently webOS 5+ _is_ supposed to work?

https://twitter.com/stek29/status/1445469374194667520

So I don't really know what's going on.

**Comment by anthonylavado** [comment]
So LG have apparently commented that they will update older versions at a later date, but no timeframe has been given. See here: https://developer.lge.com/community/forums/RetrieveForumContent.dev?detailContsId=FC03023510&sMenuId=53&contsTypeCode=QUE&prodTypeCode=TV

At any rate, it would appear that the options given above are still the only solutions (in descending priority):
- Make sure your TV is updated if it is webOS 5 or newer
- Switch to ZeroSSL
- Root the TV and install the new certificate
- Enable HTTP (limiting it as needed)

**Comment by kexxar** [comment]
Just to add to this topic that I still have this issue, meaning that there has been no update on LG side. I have an LG C1 TV and have attempted the above mentioned solutions.

- Updated to latest version of WebOS. There are no updates when performing scanning for updates.
- I have used Certbot with LetsEncrypt first, but migrated to ZeroSSL with no effect. I have used acme.sh to set up the ZeroSSL certificate. Maybe that also can have an impact.
- Rooting is not possible on the version of WebOS that I have.
- HTTP works, but would like to avoid using that approach.

It would appear that there is no real solution for this at the moment.
Another possible solution is to get an Android TV stick and see if that works. Probably does, because Android does update their root CAs.

**Comment by simonhorlick** [comment]
I was having issues after following the guide for reverse proxying jellyfin via nginx. The way the webos client loads the server scripts means you need to add a CORS header in the reverse proxy configuration like so:

```
    #add_header X-Frame-Options "SAMEORIGIN";
    add_header Cross-Origin-Resource-Policy "cross-origin" always;
```

This is using a new LG C2 and a Lets Encrypt certificate.

**Comment by the-real-naxgo** [comment]
How would this be done if using traefik as the reverse proxy?
Thanks

**Comment by soultaco83** [comment]
> How would this be done if using traefik as the reverse proxy? Thanks

I am having this issue now. I found someone say to add this to the security headers middleware. I am just waiting on my friend to test it now. 

```
securityHeaders:
  headers:
    customResponseHeaders:
      X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
      X-Forwarded-Proto: "https"
      server: ""
      Cross-Origin-Resource-Policy: "cross-origin"
```

**Comment by soultaco83** [comment]
Sadly no my user is not able to use their TV.

**Comment by the-real-naxgo** [comment]
I managed to fix my problem. Here is how.

1st, I hava a Ubuntu machine that runs my docker containers, including traefik, and jellyfin runs on my truenas machine.

I can't find the link where I fount this, but you should run 
`curl -I -X GET https://jellyfin.your.domain/`
and if you get "SAMEORIGIN" for custom Frame Options, there is your problem.
if you check the jellyfin documentation for traefik, you can see that they advise to modify this to:
`"traefik.http.middlewares.jellyfin-mw.headers.customFrameOptionsValue='allow-from https://DOMAIN_NAME'"`
But since I do not run jellyfin in docker, but on my truenas machine, I had to configure the traefik config.yml, more precisely the middlewares section where the default headers were. I also added other stuff from the jellyfin docs:
```
routers:
    jellyfin:
      entryPoints:
        - "https"
      rule: "Host(`jellyfin.your.domain`)"
      middlewares:
        # this is the bit i needed to fix
        - jelly-headers
        - https-redirectscheme
      tls: {}
      service: jellyfin

services:
  jellyfin:
    loadBalancer:
      servers:
        - url: "https://truenasIP:30013"
      passHostHeader: true

middlewares:
 jelly-headers:
  headers:
   frameDeny: true
   browserXssFilter: true
   contentTypeNosniff: true
   forceSTSHeader: true
   stsIncludeSubdomains: true
   stsPreload: true
   stsSeconds: 15552000
   customFrameOptionsValue: 'allow-from https://your.domain'
   customRequestHeaders:
      X-Forwarded-Proto: https
   customResponseHeaders:
      X-Robots-Tag: noindex,nofollow,nosn>
      X-XSS-PROTECTION: 1
```
After this, my LG tv connects over https with no issues.

Hope this helps
